[package]
name = "cordis-di-logger-console"
version = "0.1.0"
edition = "2021"
rust-version = "1.85"
description = "ANSI-colored console log exporter for cordis-di"
license = "MIT"
homepage = "https://github.com/Ricardo-M-L/cordis-di"
repository = "https://github.com/Ricardo-M-L/cordis-di"

[dependencies]
cordis-di-core = { version = "0.1.0", path = "../cordis-core" }
serde = { version = "1", features = ["derive"] }
